import { BackupRecord, StorageDestination, Client } from './types';

export const RECENT_BACKUPS: BackupRecord[] = [
  {
    id: 'BKP-9021',
    status: 'failed',
    client: 'Aditus Consultoria',
    category: 'Rotina',
    title: 'Validação Diária de Backups - Aditus (19/03)',
    timestamp: '19/03/2026 10:53',
    responsible: 'João Santos',
  },
  {
    id: 'BKP-9020',
    status: 'success',
    client: 'Fundação Abrinq',
    category: 'Rotina',
    title: 'Validação Diária de Backups - FAB (19/03)',
    timestamp: '19/03/2026 10:57',
    responsible: 'João Santos',
  },
  {
    id: 'BKP-9019',
    status: 'success',
    client: 'G5 Engenharia',
    category: 'Rotina',
    title: 'Validação Diária de Backups - G5 (19/03)',
    timestamp: '19/03/2026 11:00',
    responsible: 'João Santos',
  },
  {
    id: 'BKP-9018',
    status: 'success',
    client: 'Aliplast',
    category: 'Rotina',
    title: 'Validação Diária de Backups - Clientes S3 (19/03)',
    timestamp: '19/03/2026 11:03',
    responsible: 'João Santos',
  },
  {
    id: 'BKP-9017',
    status: 'success',
    client: 'CAW',
    category: 'Rotina',
    title: 'Validação Diária de Backups - Clientes S3 (19/03)',
    timestamp: '19/03/2026 11:05',
    responsible: 'João Santos',
  },
  {
    id: 'BKP-9016',
    status: 'success',
    client: 'Aroma da Carne',
    category: 'Rotina',
    title: 'Validação Diária de Backups - Clientes S3 (19/03)',
    timestamp: '19/03/2026 11:06',
    responsible: 'João Santos',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  { id: '1', name: 'Aditus Consultoria', createdAt: '19/03/2026' },
  { id: '2', name: 'Fundação Abrinq', createdAt: '19/03/2026' },
  { id: '3', name: 'G5 Engenharia', createdAt: '19/03/2026' },
  { id: '4', name: 'Aliplast', createdAt: '19/03/2026' },
  { id: '5', name: 'CAW', createdAt: '19/03/2026' },
  { id: '6', name: 'Aroma da Carne', createdAt: '19/03/2026' },
];

export const STORAGE_DESTINATIONS: StorageDestination[] = [
  {
    id: '1',
    name: 'G7_S3_ADT',
    client: 'Aditus Consultoria',
    freeSpaceTB: 16.32,
    usedSpaceTB: 15.68,
    totalSpaceTB: 32.0,
    savingsPercent: 45,
    savingsTB: 12.8,
    backupsCount: 150,
    location: 'S3',
  },
  {
    id: '2',
    name: 'Repo-Imutavel',
    client: 'Fundação Abrinq',
    freeSpaceTB: 40.04,
    usedSpaceTB: 38.88,
    totalSpaceTB: 78.92,
    savingsPercent: 46,
    savingsTB: 33.12,
    backupsCount: 245,
    location: 'Local',
  },
  {
    id: '3',
    name: 'G7_S3_ALI',
    client: 'Aliplast',
    freeSpaceTB: 0.35,
    usedSpaceTB: 0.1,
    totalSpaceTB: 0.45,
    savingsPercent: 15,
    savingsTB: 0.05,
    backupsCount: 42,
    location: 'S3',
  },
];
